<?php

return [
  [
    'module' => 11.5,
    'label' => 'Основы языка PHP',
    'path' => '?module=11.5',
    'icon' => '',
    'blank' => false,
    'caption' => '',
  ], [
    'module' => 11.6,
    'label' => 'Типы данных. Операции над числами и строками',
    'path' => '?module=11.6',
    'icon' => '',
    'blank' => false,
    'caption' => '',
  ], [
    'module' => 12.2,
    'label' => 'Арифметика',
    'path' => '?module=12.2',
    'icon' => '',
    'blank' => false,
    'caption' => '',
  ], [
    'module' => 12.4,
    'label' => 'Строки',
    'path' => '?module=12.4',
    'icon' => '',
    'blank' => false,
    'caption' => '',
  ], [
    'module' => 12.5,
    'label' => 'Массивы',
    'path' => '?module=12.5',
    'icon' => '',
    'blank' => false,
    'caption' => '',
  ], [
    'module' => 13,
    'label' => 'Основные алгоритмические конструкции',
    'path' => '?module=13',
    'icon' => '',
    'blank' => false,
    'caption' => '',
  ], [
    'module' => 14,
    'label' => 'Сессии и Cookie',
    'path' => '?module=14',
    'icon' => '',
    'blank' => false,
    'caption' => '',
  ], [
    'module' => 16.2,
    'label' => 'Базы данных',
    'path' => '?module=16.2',
    'icon' => '',
    'blank' => false,
    'caption' => '',
  ], [
    'module' => 16.4,
    'label' => 'MySQL',
    'path' => '?module=16.4',
    'icon' => '',
    'blank' => false,
    'caption' => '',
  ], [
    'module' => 17.3,
    'label' => 'PostgreSQL & DBeaver',
    'path' => '?module=17.3',
    'icon' => '',
    'blank' => false,
    'caption' => '',
  ], [
    'module' => 17.4,
    'label' => '',
    'path' => '?module=17.4',
    'icon' => '',
    'blank' => false,
    'caption' => '',
  ], [
    'module' => 17.5,
    'label' => '',
    'path' => '?module=17.5',
    'icon' => '',
    'blank' => false,
    'caption' => '',
  ], [
    'module' => 17.6,
    'label' => '',
    'path' => '?module=17.6',
    'icon' => '',
    'blank' => false,
    'caption' => '',
  ], [
    'module' => 17.7,
    'label' => '',
    'path' => '?module=17.7',
    'icon' => '',
    'blank' => false,
    'caption' => '',
  ], [
    'module' => 17.8,
    'label' => '',
    'path' => '?module=17.8',
    'icon' => '',
    'blank' => false,
    'caption' => '',
  ], [
    'module' => 18.2,
    'label' => '',
    'path' => '?module=18.2',
    'icon' => '',
    'blank' => false,
    'caption' => '',
  ], [
    'module' => 18.4,
    'label' => '',
    'path' => '?module=18.4',
    'icon' => '',
    'blank' => false,
    'caption' => '',
  ], [
    'module' => 18.5,
    'label' => '',
    'path' => '?module=18.5',
    'icon' => '',
    'blank' => false,
    'caption' => '',
  ], [
    'module' => 19.2,
    'label' => '',
    'path' => '?module=19.2',
    'icon' => '',
    'blank' => false,
    'caption' => '',
  ], [
    'module' => 23.3,
    'label' => 'Объекты и классы',
    'path' => '?module=23.3',
    'icon' => '',
    'blank' => false,
    'caption' => '',
  ], [
    'module' => 23.4,
    'label' => 'Инкапсуляция',
    'path' => '?module=23.4',
    'icon' => '',
    'blank' => false,
    'caption' => '',
  ], [
    'module' => 23.5,
    'label' => 'Наследование',
    'path' => '?module=23.5',
    'icon' => '',
    'blank' => false,
    'caption' => '',
  ], [
    'module' => 23.6,
    'label' => 'Полиморфизм',
    'path' => '?module=23.6',
    'icon' => '',
    'blank' => false,
    'caption' => '',
  ], [
    'module' => 23.7,
    'label' => 'Абстрактные классы и интерфейсы',
    'path' => '?module=23.7',
    'icon' => '',
    'blank' => false,
    'caption' => '',
  ], [
    'module' => 23.9,
    'label' => 'Магические методы',
    'path' => '?module=23.9',
    'icon' => '',
    'blank' => false,
    'caption' => '',
  ],
];
